'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api';
type User = { username: string; employee: { firstName: string; lastName: string; employeeNumber: string } };
type Role = { code: string; name: string; permissions: Array<{ code: string; scope: string }> };
type Review = { id: string; status: string };

export default function HomePage() {
  const router = useRouter(); const [user, setUser] = useState<User | null>(null); const [roles, setRoles] = useState<Role[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${API}/auth/me`, { credentials: 'include' }).then(async r => { if (!r.ok) throw new Error('unauthenticated'); return r.json(); }).then(async data => { setUser(data.user); setRoles(data.roles ?? []); const response = await fetch(`${API}/performance/reviews/mine`, { credentials: 'include' }); if (response.ok) setReviews(await response.json()); }).catch(() => router.replace('/login')).finally(() => setLoading(false)); }, [router]);
  async function logout() { await fetch(`${API}/auth/logout`, { method: 'POST', credentials: 'include' }); router.replace('/login'); }
  if (loading) return <main className="loading">Loading workspace…</main>; if (!user) return null;
  const codes = new Set(roles.map(role => role.code)); const isIT = codes.has('IT_ADMIN') || codes.has('SUPER_ADMIN'); const isPmsAdmin = codes.has('PMS_ADMIN') || codes.has('SUPER_ADMIN'); const isSupervisor = codes.has('SUPERVISOR') || codes.has('HOD');
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>PMS</span><small>Performance Management</small></div><nav><a className="active">Overview</a><a onClick={() => router.push('/reviews')}>My Reviews</a>{isSupervisor && <a onClick={() => router.push('/team-reviews')}>Team Reviews</a>}{isPmsAdmin && <a onClick={() => router.push('/performance-setup')}>Performance Setup</a>}{isIT && <a onClick={() => router.push('/admin/it')}>IT Administration</a>}</nav><button className="logout" onClick={logout}>Sign out</button></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">Workspace</p><h1>Good to see you, {user.employee.firstName}</h1></div><div className="avatar">{user.employee.firstName[0]}{user.employee.lastName[0]}</div></header><div className="content"><section className="hero-panel"><div><p className="eyebrow">Performance dashboard</p><h2>Keep performance moving forward.</h2><p>Track reviews, goals, feedback and approvals from one controlled workspace.</p></div><span className="status-pill">● Account active</span></section><div className="stat-grid"><article><span>My reviews</span><strong>{reviews.length}</strong><small>Reviews assigned to you</small></article><article><span>Pending actions</span><strong>{reviews.filter(r => ['RETURNED', 'RESUBMITTED', 'IN_PROGRESS'].includes(r.status)).length}</strong><small>Items needing attention</small></article><article><span>Current role</span><strong>{roles[0]?.name ?? 'Employee'}</strong><small>{user.employee.employeeNumber}</small></article></div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Quick access</p><h3>Your workspace</h3></div></div><div className="quick-grid"><button onClick={() => router.push('/reviews')}>Open my reviews <span>→</span></button>{isSupervisor && <button onClick={() => router.push('/team-reviews')}>Review my team <span>→</span></button>}{isPmsAdmin && <button onClick={() => router.push('/performance-setup')}>Manage performance setup <span>→</span></button>}{isIT && <button onClick={() => router.push('/admin/it')}>Open IT administration <span>→</span></button>}</div></section></div></section></main>;
}
