'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000';
type Organisation = { id: string; name: string; code: string; description?: string | null; isActive: boolean; _count: { departments: number; designations: number; employees: number } };
type Department = { id: string; name: string; code: string; parent?: { name: string } | null; _count: { employees: number; children: number } };
type Designation = { id: string; name: string; code?: string | null; grade?: string | null; _count: { employees: number } };
type Employee = { id: string; employeeNumber: string; user?: { id: string; username: string; firstName: string; lastName: string; email?: string | null; isActive: boolean } | null; department?: { name: string } | null; designation?: { name: string; grade?: string | null } | null; manager?: { employeeNumber: string; user: { firstName: string; lastName: string } } | null };
type User = { id: string; username: string; firstName: string; lastName: string; employee?: { id: string } | null };

async function request(path: string, options: RequestInit = {}) {
  const token = localStorage.getItem('pms_token');
  return fetch(`${API}${path}`, { ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(options.headers ?? {}) } });
}

export default function OrganisationAdmin() {
  const [organisations, setOrganisations] = useState<Organisation[]>([]); const [organisationId, setOrganisationId] = useState('');
  const [departments, setDepartments] = useState<Department[]>([]); const [designations, setDesignations] = useState<Designation[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [users, setUsers] = useState<User[]>([]);
  const [message, setMessage] = useState(''); const [orgForm, setOrgForm] = useState({ name: '', code: '', description: '' }); const [editForm, setEditForm] = useState({ name: '', code: '', description: '', isActive: true });
  const [deptForm, setDeptForm] = useState({ name: '', code: '', parentId: '' }); const [designationForm, setDesignationForm] = useState({ name: '', code: '', grade: '' }); const [employeeForm, setEmployeeForm] = useState({ userId: '', employeeNumber: '', departmentId: '', designationId: '', managerId: '' }); const [unlinkedEmployeeForm, setUnlinkedEmployeeForm] = useState({ employeeNumber: '', departmentId: '', designationId: '', managerId: '' }); const [accountForm, setAccountForm] = useState({ employeeId: '', username: '', password: '', firstName: '', lastName: '', email: '' });

  async function loadOrganisations() {
    const response = await request('/organisation'); if (!response.ok) { setMessage('Unable to load organisations.'); return; }
    const data = await response.json(); setOrganisations(data); const saved = localStorage.getItem('pms_organisation_id'); const selected = saved && data.some((x: Organisation) => x.id === saved) ? saved : data[0]?.id ?? ''; setOrganisationId(selected);
  }
  async function loadOrganisationData(id: string) {
    if (!id) return; localStorage.setItem('pms_organisation_id', id); const selected = organisations.find(o => o.id === id); if (selected) setEditForm({ name: selected.name, code: selected.code, description: selected.description ?? '', isActive: selected.isActive });
    const [d, g, e, u] = await Promise.all([request(`/organisation/${id}/departments`), request(`/organisation/${id}/designations`), request(`/organisation/${id}/employees`), request('/admin/users')]);
    if (d.ok) setDepartments(await d.json()); if (g.ok) setDesignations(await g.json()); if (e.ok) setEmployees(await e.json()); if (u.ok) setUsers(await u.json());
  }
  useEffect(() => { loadOrganisations(); }, []); useEffect(() => { loadOrganisationData(organisationId); }, [organisationId]);

  async function createOrganisation(event: React.FormEvent) { event.preventDefault(); const r = await request('/organisation', { method: 'POST', body: JSON.stringify(orgForm) }); if (!r.ok) { setMessage(await r.text()); return; } setOrgForm({ name: '', code: '', description: '' }); setMessage('Organisation created.'); await loadOrganisations(); }
  async function updateOrganisation(event: React.FormEvent) { event.preventDefault(); const r = await request(`/organisation/${organisationId}`, { method: 'PATCH', body: JSON.stringify(editForm) }); if (!r.ok) { setMessage(await r.text()); return; } setMessage('Organisation updated.'); await loadOrganisations(); }
  async function createDepartment(event: React.FormEvent) { event.preventDefault(); const r = await request(`/organisation/${organisationId}/departments`, { method: 'POST', body: JSON.stringify({ ...deptForm, parentId: deptForm.parentId || undefined }) }); if (!r.ok) { setMessage(await r.text()); return; } setDeptForm({ name: '', code: '', parentId: '' }); setMessage('Department created.'); loadOrganisationData(organisationId); }
  async function createDesignation(event: React.FormEvent) { event.preventDefault(); const r = await request(`/organisation/${organisationId}/designations`, { method: 'POST', body: JSON.stringify({ ...designationForm, code: designationForm.code || undefined, grade: designationForm.grade || undefined }) }); if (!r.ok) { setMessage(await r.text()); return; } setDesignationForm({ name: '', code: '', grade: '' }); setMessage('Designation created.'); loadOrganisationData(organisationId); }
  async function assignEmployee(event: React.FormEvent) { event.preventDefault(); const r = await request(`/organisation/${organisationId}/employees`, { method: 'POST', body: JSON.stringify({ ...employeeForm, departmentId: employeeForm.departmentId || undefined, designationId: employeeForm.designationId || undefined, managerId: employeeForm.managerId || undefined }) }); if (!r.ok) { setMessage(await r.text()); return; } setEmployeeForm({ userId: '', employeeNumber: '', departmentId: '', designationId: '', managerId: '' }); setMessage('Employee assignment saved.'); loadOrganisationData(organisationId); }
  async function createUnlinkedEmployee(event: React.FormEvent) { event.preventDefault(); const r = await request('/organisation/' + organisationId + '/employees/unlinked', { method: 'POST', body: JSON.stringify({ ...unlinkedEmployeeForm, departmentId: unlinkedEmployeeForm.departmentId || undefined, designationId: unlinkedEmployeeForm.designationId || undefined, managerId: unlinkedEmployeeForm.managerId || undefined }) }); if (!r.ok) { setMessage(await r.text()); return; } setUnlinkedEmployeeForm({ employeeNumber: '', departmentId: '', designationId: '', managerId: '' }); setMessage('Employee record created without a login account.'); loadOrganisationData(organisationId); }
  async function createEmployeeAccount(event: React.FormEvent) { event.preventDefault(); const r = await request('/admin/employees/' + accountForm.employeeId + '/account', { method: 'POST', body: JSON.stringify({ username: accountForm.username, password: accountForm.password, firstName: accountForm.firstName || undefined, lastName: accountForm.lastName || undefined, email: accountForm.email || undefined }) }); if (!r.ok) { setMessage(await r.text()); return; } setAccountForm({ employeeId: '', username: '', password: '', firstName: '', lastName: '', email: '' }); setMessage('Login account created.'); loadOrganisationData(organisationId); }
  const availableUsers = users.filter(user => !user.employee || employees.some(employee => employee.user?.id === user.id)); const unlinkedEmployees = employees.filter(employee => !employee.user); const selectedOrg = organisations.find(o => o.id === organisationId);

  return <main className="shell"><section className="card"><p className="eyebrow">SYSTEM ADMINISTRATION</p><h1>Organisation administration</h1><p>Configure organisations, departments, positions, employees and reporting relationships.</p><div className="actions"><Link className="button secondary" href="/admin">Back to administration</Link></div>{message && <p className="muted">{message}</p>}
    <div className="card"><h2>Organisation</h2><label>Active organisation<select value={organisationId} onChange={e => setOrganisationId(e.target.value)}><option value="">Select organisation…</option>{organisations.map(o => <option key={o.id} value={o.id}>{o.name} ({o.code})</option>)}</select></label>{selectedOrg && <p className="muted">{selectedOrg._count.employees} employees · {selectedOrg._count.departments} departments · {selectedOrg._count.designations} designations</p>}
      {organisationId && <form className="form" onSubmit={updateOrganisation}><h3>Edit selected organisation</h3><label>Name<input value={editForm.name} onChange={e => setEditForm({ ...editForm, name: e.target.value })} required /></label><label>Code<input value={editForm.code} onChange={e => setEditForm({ ...editForm, code: e.target.value })} required /></label><label>Description<input value={editForm.description} onChange={e => setEditForm({ ...editForm, description: e.target.value })} /></label><label><input type="checkbox" checked={editForm.isActive} onChange={e => setEditForm({ ...editForm, isActive: e.target.checked })} /> Active</label><button className="button">Save organisation</button></form>}
      <form className="form" onSubmit={createOrganisation}><h3>New organisation</h3><label>Name<input value={orgForm.name} onChange={e => setOrgForm({ ...orgForm, name: e.target.value })} required /></label><label>Code<input value={orgForm.code} onChange={e => setOrgForm({ ...orgForm, code: e.target.value })} required /></label><label>Description<input value={orgForm.description} onChange={e => setOrgForm({ ...orgForm, description: e.target.value })} /></label><button className="button">Create organisation</button></form>
    </div>
    {organisationId && <><div className="grid"><div className="card"><h2>Departments</h2><form className="form" onSubmit={createDepartment}><label>Name<input value={deptForm.name} onChange={e => setDeptForm({ ...deptForm, name: e.target.value })} required /></label><label>Code<input value={deptForm.code} onChange={e => setDeptForm({ ...deptForm, code: e.target.value })} required /></label><label>Parent<select value={deptForm.parentId} onChange={e => setDeptForm({ ...deptForm, parentId: e.target.value })}><option value="">Top level</option>{departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="button">Add department</button></form><ul>{departments.map(d => <li key={d.id}><strong>{d.name}</strong> ({d.code}){d.parent ? ` · under ${d.parent.name}` : ''} · {d._count.employees} staff</li>)}</ul></div><div className="card"><h2>Designations</h2><form className="form" onSubmit={createDesignation}><label>Name<input value={designationForm.name} onChange={e => setDesignationForm({ ...designationForm, name: e.target.value })} required /></label><label>Code<input value={designationForm.code} onChange={e => setDesignationForm({ ...designationForm, code: e.target.value })} /></label><label>Grade<input value={designationForm.grade} onChange={e => setDesignationForm({ ...designationForm, grade: e.target.value })} placeholder="e.g. GL 08" /></label><button className="button">Add designation</button></form><ul>{designations.map(d => <li key={d.id}><strong>{d.name}</strong>{d.grade ? ` · ${d.grade}` : ''}{d.code ? ` · ${d.code}` : ''} · {d._count.employees} staff</li>)}</ul></div></div>
      <div className="card"><h2>Employee assignment</h2><p>Link a system user to an employee record and place them in the organisation hierarchy.</p><form className="form" onSubmit={assignEmployee}><label>User<select value={employeeForm.userId} onChange={e => setEmployeeForm({ ...employeeForm, userId: e.target.value })} required><option value="">Select user…</option>{availableUsers.map(u => <option key={u.id} value={u.id}>{u.firstName} {u.lastName} (@{u.username})</option>)}</select></label><label>Employee number<input value={employeeForm.employeeNumber} onChange={e => setEmployeeForm({ ...employeeForm, employeeNumber: e.target.value })} required placeholder="EMP-0001" /></label><label>Department<select value={employeeForm.departmentId} onChange={e => setEmployeeForm({ ...employeeForm, departmentId: e.target.value })}><option value="">Not assigned</option>{departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Designation<select value={employeeForm.designationId} onChange={e => setEmployeeForm({ ...employeeForm, designationId: e.target.value })}><option value="">Not assigned</option>{designations.map(d => <option key={d.id} value={d.id}>{d.name}{d.grade ? ` · ${d.grade}` : ''}</option>)}</select></label><label>Manager<select value={employeeForm.managerId} onChange={e => setEmployeeForm({ ...employeeForm, managerId: e.target.value })}><option value="">No manager</option>{employees.filter(e => e.user && e.user.id !== employeeForm.userId).map(e => <option key={e.id} value={e.id}>{e.user?.firstName} {e.user?.lastName} · {e.employeeNumber}</option>)}</select></label><button className="button">Save employee assignment</button></form></div>
      <div className="grid"><div className="card"><h2>Employee-first provisioning</h2><p>Create a personnel record before a login account exists.</p><form className="form" onSubmit={createUnlinkedEmployee}><label>Employee number<input value={unlinkedEmployeeForm.employeeNumber} onChange={e => setUnlinkedEmployeeForm({ ...unlinkedEmployeeForm, employeeNumber: e.target.value })} required /></label><label>Department<select value={unlinkedEmployeeForm.departmentId} onChange={e => setUnlinkedEmployeeForm({ ...unlinkedEmployeeForm, departmentId: e.target.value })}><option value="">Not assigned</option>{departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Designation<select value={unlinkedEmployeeForm.designationId} onChange={e => setUnlinkedEmployeeForm({ ...unlinkedEmployeeForm, designationId: e.target.value })}><option value="">Not assigned</option>{designations.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="button">Create employee record</button></form></div><div className="card"><h2>Create login for employee</h2><p>Provision an account later for a personnel record.</p><form className="form" onSubmit={createEmployeeAccount}><label>Employee<select value={accountForm.employeeId} onChange={e => setAccountForm({ ...accountForm, employeeId: e.target.value })} required><option value="">Select employee…</option>{unlinkedEmployees.map(e => <option key={e.id} value={e.id}>{e.employeeNumber}</option>)}</select></label><label>Username<input value={accountForm.username} onChange={e => setAccountForm({ ...accountForm, username: e.target.value })} required /></label><label>Password<input type="password" minLength={10} value={accountForm.password} onChange={e => setAccountForm({ ...accountForm, password: e.target.value })} required /></label><label>First name<input value={accountForm.firstName} onChange={e => setAccountForm({ ...accountForm, firstName: e.target.value })} /></label><label>Last name<input value={accountForm.lastName} onChange={e => setAccountForm({ ...accountForm, lastName: e.target.value })} /></label><label>Email<input type="email" value={accountForm.email} onChange={e => setAccountForm({ ...accountForm, email: e.target.value })} /></label><button className="button">Create login</button></form></div></div>
      <div className="card"><h2>Employees</h2>{employees.length === 0 ? <p className="muted">No employees assigned to this organisation yet.</p> : <div className="grid">{employees.map(e => <article key={e.id}><strong>{e.user ? `${e.user.firstName} ${e.user.lastName}` : 'Unlinked employee'}</strong><p>{e.employeeNumber}{e.user ? ` · @${e.user.username}` : ' · No login account'}</p><p>{e.department?.name ?? 'No department'} · {e.designation?.name ?? 'No designation'}</p><p>Manager: {e.manager ? `${e.manager.user.firstName} ${e.manager.user.lastName}` : 'None'}</p></article>)}</div>}</div></>}
  </section></main>;
}
