'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api';
type Review = { id: string; status: string; employee: { firstName: string; lastName: string; employeeNumber: string }; performanceCycle: { name: string; program: { name: string } }; reviewType: { name: string }; kpis: Array<{ id: string; title: string; target: string | null; weight: number; employeeScore: number | null; supervisorScore: number | null }>; competencies: Array<{ id: string; weight: number; competency: { name: string }; employeeRating: number | null; supervisorRating: number | null }>; scores: Array<{ overallScore: number | null; overallRating: string | null }> };

export default function ReviewDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [review, setReview] = useState<Review | null>(null); const [error, setError] = useState('');
  useEffect(() => { fetch(`${API}/performance/reviews/${id}`, { credentials: 'include' }).then(async r => { if (r.status === 401) { router.replace('/login'); return null; } if (!r.ok) throw new Error('Unable to load this review'); return r.json(); }).then(setReview).catch(e => setError(e.message)); }, [id, router]);
  if (error) return <main className="loading">{error}</main>; if (!review) return <main className="loading">Loading review…</main>;
  const score = review.scores[0];
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>PMS</span><small>Performance Management</small></div><nav><a onClick={() => router.push('/')}>Overview</a><a className="active">Review</a></nav></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">{review.performanceCycle.program.name}</p><h1>{review.performanceCycle.name}</h1></div><button className="back-button" onClick={() => router.back()}>Back</button></header><div className="content"><section className="hero-panel"><div><p className="eyebrow">{review.reviewType.name}</p><h2>{review.employee.firstName} {review.employee.lastName}</h2><p>{review.employee.employeeNumber}</p></div><span className={`status status-${review.status.toLowerCase()}`}>{review.status.replaceAll('_', ' ')}</span></section><div className="stat-grid"><article><span>Overall score</span><strong>{score?.overallScore != null ? `${Number(score.overallScore).toFixed(1)}%` : '—'}</strong><small>{score?.overallRating ?? 'Not calculated'}</small></article><article><span>KPIs</span><strong>{review.kpis.length}</strong><small>Assigned measures</small></article><article><span>Competencies</span><strong>{review.competencies.length}</strong><small>Behavioural measures</small></article></div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Performance measures</p><h3>KPIs</h3></div></div><div className="review-list">{review.kpis.map(k => <div className="review-row static" key={k.id}><div><strong>{k.title}</strong><span>{k.target ? `Target: ${k.target}` : 'No target specified'} · Weight {k.weight}</span></div><div className="review-meta"><span>Employee: {k.employeeScore ?? '—'}</span><strong>Supervisor: {k.supervisorScore ?? '—'}</strong></div></div>)}</div></section><section className="panel detail-panel"><div className="panel-heading"><div><p className="eyebrow">Behaviour</p><h3>Competencies</h3></div></div><div className="review-list">{review.competencies.map(c => <div className="review-row static" key={c.id}><div><strong>{c.competency.name}</strong><span>Weight {c.weight}</span></div><div className="review-meta"><span>Employee: {c.employeeRating ?? '—'}</span><strong>Supervisor: {c.supervisorRating ?? '—'}</strong></div></div>)}</div></section></div></section></main>;
}
