'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api';
type Review = { id: string; status: string; employee: { id: string; firstName: string; lastName: string; employeeNumber: string }; performanceCycle: { name: string; program: { name: string } }; reviewType: { name: string }; kpis: Array<{ id: string; title: string; target: string | null; measurementUnit: string | null; weight: number; employeeScore: number | null; supervisorScore: number | null; employeeComment: string | null; supervisorComment: string | null }>; competencies: Array<{ id: string; competency: { name: string }; weight: number; employeeRating: number | null; supervisorRating: number | null; employeeComment: string | null; supervisorComment: string | null }>; scores: Array<{ overallScore: number | null; overallRating: string | null; calculatedAt: string }> };
type Me = { employee: { id: string }; roles: Array<{ code: string }> };
type Workflow = { status: string; currentStep: { name: string; actorType: string } | null; actions: Array<{ action: string; comment: string | null; createdAt: string; user: { employee: { firstName: string; lastName: string } } }> } | null;

const terminalStatuses = ['FINALIZED', 'LOCKED', 'CANCELLED'];

export default function ReviewDetailPage() {
  const params = useParams<{ reviewId: string }>(); const router = useRouter();
  const [review, setReview] = useState<Review | null>(null); const [workflow, setWorkflow] = useState<Workflow>(null); const [canEdit, setCanEdit] = useState(false); const [canSupervise, setCanSupervise] = useState(false); const [canFinalize, setCanFinalize] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState<string | null>(null); const [delegateToUserId, setDelegateToUserId] = useState('');

  async function load() {
    try {
      const meResponse = await fetch(`${API}/auth/me`, { credentials: 'include' });
      if (meResponse.status === 401) { router.replace('/login'); return; }
      if (!meResponse.ok) throw new Error('Unable to identify current user');
      const me: { user: Me } = await meResponse.json();
      const [mineResponse, teamResponse, workflowResponse] = await Promise.all([
        fetch(`${API}/performance/reviews/mine`, { credentials: 'include' }),
        fetch(`${API}/performance/reviews/team`, { credentials: 'include' }),
        fetch(`${API}/performance/reviews/${params.reviewId}/workflow`, { credentials: 'include' }),
      ]);
      const mine: Review[] = mineResponse.ok ? await mineResponse.json() : [];
      const team: Review[] = teamResponse.ok ? await teamResponse.json() : [];
      const found = [...mine, ...team].find(item => item.id === params.reviewId) ?? null;
      if (!found) throw new Error('You do not have access to this review');
      const supervisorRole = me.user.roles.some(role => ['SUPERVISOR', 'HOD', 'SUPER_ADMIN'].includes(role.code));
      const finalizeRole = me.user.roles.some(role => ['PMS_ADMIN', 'HR_OFFICER', 'SUPER_ADMIN'].includes(role.code));
      setReview(found); setWorkflow(workflowResponse.ok ? await workflowResponse.json() : null); setCanEdit(found.employee.id === me.user.employee.id); setCanSupervise(supervisorRole && found.employee.id !== me.user.employee.id); setCanFinalize(finalizeRole);
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load review'); }
    finally { setLoading(false); }
  }
  useEffect(() => { load(); }, [params.reviewId]);

  async function post(path: string, key: string, body: unknown = {}) {
    setSaving(key); setError('');
    try {
      const response = await fetch(`${API}${path}`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      if (!response.ok) { let message = 'The action could not be completed'; try { const data = await response.json(); message = data.message ?? message; } catch {} setError(message); }
      else await load();
    } finally { setSaving(null); }
  }
  async function saveKpi(id: string, score: string, comment: string, actor: 'employee' | 'supervisor') { await post(`/performance/reviews/${params.reviewId}/kpis/${id}/${actor === 'employee' ? 'employee-score' : 'supervisor-score'}`, id, { score: Number(score), comment }); }
  async function saveCompetency(id: string, rating: string, comment: string, actor: 'employee' | 'supervisor') { await post(`/performance/reviews/${params.reviewId}/competencies/${id}/${actor === 'employee' ? 'employee-rating' : 'supervisor-rating'}`, id, { rating: Number(rating), comment }); }
  async function submit() { await post(`/performance/reviews/${params.reviewId}/submit`, 'submit'); }
  async function workflowAction(action: 'approve' | 'return' | 'reject') { await post(`/performance/reviews/${params.reviewId}/${action}`, action); }
  async function calculateScore() { await post(`/performance/reviews/${params.reviewId}/calculate-score`, 'calculate-score'); }
  async function finalizeReview() { await post(`/performance/reviews/${params.reviewId}/finalize`, 'finalize'); }
  async function delegateReview() { if (!delegateToUserId.trim()) { setError('Enter the user ID to whom this review should be delegated.'); return; } await post(`/performance/reviews/${params.reviewId}/delegate`, 'delegate', { delegateToUserId: delegateToUserId.trim(), comment: 'Workflow delegation' }); setDelegateToUserId(''); }

  if (loading) return <main className="loading">Loading review…</main>;
  if (!review) return <main className="content"><p className="error">{error || 'Review not found.'}</p></main>;
  const latest = review.scores[0]; const editable = canEdit && ![...terminalStatuses, 'APPROVED'].includes(review.status); const supervisorEditable = canSupervise && !terminalStatuses.includes(review.status); const workflowReady = ['SUBMITTED', 'UNDER_REVIEW', 'RESUBMITTED'].includes(review.status); const approved = review.status === 'APPROVED';
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>PMS</span><small>Performance Management</small></div><nav><a onClick={() => router.push('/')}>Overview</a><a className="active" onClick={() => router.push(canSupervise ? '/team-reviews' : '/reviews')}>{canSupervise ? 'Team Reviews' : 'My Reviews'}</a></nav></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">Performance review</p><h1>{review.performanceCycle.name}</h1></div><button className="back-button" onClick={() => router.push(canSupervise ? '/team-reviews' : '/reviews')}>Back to reviews</button></header><div className="content">{error && <p className="error">{error}</p>}<section className="review-summary"><div><p className="eyebrow">{review.performanceCycle.program.name} · {review.reviewType.name}</p><h2>{review.employee.firstName} {review.employee.lastName}</h2><p className="muted">Employee {review.employee.employeeNumber}</p></div><div className="review-score"><span className={`status status-${review.status.toLowerCase()}`}>{review.status.replaceAll('_', ' ')}</span><strong>{latest?.overallScore != null ? `${Number(latest.overallScore).toFixed(1)}%` : '—'}</strong><small>{latest?.overallRating ?? 'Overall score not calculated'}</small></div></section>
    {workflow && <section className="panel review-section"><div className="panel-heading"><div><p className="eyebrow">Workflow</p><h3>{workflow.currentStep ? `Current step: ${workflow.currentStep.name}` : 'Workflow complete'}</h3></div><span className="status">{workflow.status.replaceAll('_', ' ')}</span></div>{workflow.currentStep && <p className="muted">Assigned actor: {workflow.currentStep.actorType.replaceAll('_', ' ')}</p>}<div className="workflow-timeline">{workflow.actions.map((action, index) => <div className="workflow-event" key={`${action.createdAt}-${index}`}><strong>{action.action.replaceAll('_', ' ')}</strong><span>{action.user.employee.firstName} {action.user.employee.lastName} · {new Date(action.createdAt).toLocaleString()}</span>{action.comment && <p>{action.comment}</p>}</div>)}</div>{workflowReady && <div className="builder-actions"><label>User ID for delegation<input value={delegateToUserId} disabled={saving !== null} onChange={e => setDelegateToUserId(e.target.value)} placeholder="UUID" /></label><button disabled={saving !== null || !delegateToUserId.trim()} onClick={delegateReview}>{saving === 'delegate' ? 'Delegating…' : 'Delegate'}</button></div>}</section>}
    {canSupervise && <section className="panel review-section"><div className="panel-heading"><div><p className="eyebrow">Supervisor review</p><h3>Review employee submission</h3></div><span className="muted">Employee scores remain read-only</span></div><p className="muted">Enter your independent assessment below. The supervisor score takes precedence when the overall performance score is calculated.</p></section>}
    <section className="panel review-section"><div className="panel-heading"><div><p className="eyebrow">Key performance indicators</p><h3>Goals and results</h3></div></div>{review.kpis.length === 0 ? <p className="muted">No KPIs are attached to this review.</p> : <div className="review-items">{review.kpis.map(k => <KpiEditor key={k.id} kpi={k} editable={editable} supervisorEditable={supervisorEditable} saving={saving === k.id} onSave={saveKpi} />)}</div>}</section>
    <section className="panel review-section"><div className="panel-heading"><div><p className="eyebrow">Competencies</p><h3>Behaviour and capability</h3></div></div>{review.competencies.length === 0 ? <p className="muted">No competencies are attached to this review.</p> : <div className="review-items">{review.competencies.map(c => <CompetencyEditor key={c.id} competency={c} editable={editable} supervisorEditable={supervisorEditable} saving={saving === c.id} onSave={saveCompetency} />)}</div>}</section>
    {editable && <section className="review-actions"><p className="muted">Review your entries before submitting. Once submitted, the workflow routes the review to the configured next actor.</p><button className="primary-action" disabled={saving !== null} onClick={submit}>{saving === 'submit' ? 'Submitting…' : 'Submit review'}</button></section>}
    {canSupervise && workflowReady && <section className="review-actions"><div><p className="eyebrow">Workflow action</p><h3>Supervisor decision</h3><p className="muted">Approve when the assessment is complete, or return/reject it when changes are required.</p></div><div className="action-row"><button className="primary-action" disabled={saving !== null} onClick={calculateScore}>{saving === 'calculate-score' ? 'Calculating…' : 'Calculate score'}</button><button className="primary-action" disabled={saving !== null} onClick={() => workflowAction('approve')}>{saving === 'approve' ? 'Approving…' : 'Approve review'}</button><button disabled={saving !== null} onClick={() => workflowAction('return')}>{saving === 'return' ? 'Returning…' : 'Return to employee'}</button><button disabled={saving !== null} onClick={() => workflowAction('reject')}>{saving === 'reject' ? 'Rejecting…' : 'Reject review'}</button></div></section>}
    {canFinalize && approved && <section className="review-actions"><div><p className="eyebrow">Finalization</p><h3>Lock the completed review</h3><p className="muted">Finalization is the administrative step after workflow approval. The backend verifies the workflow, assessments and final score before locking the record.</p></div><div className="action-row"><button className="primary-action" disabled={saving !== null} onClick={calculateScore}>{saving === 'calculate-score' ? 'Calculating…' : 'Recalculate final score'}</button><button className="primary-action" disabled={saving !== null} onClick={finalizeReview}>{saving === 'finalize' ? 'Finalizing…' : 'Finalize review'}</button></div></section>}
  </div></section></main>;
}

function KpiEditor({ kpi, editable, supervisorEditable, saving, onSave }: { kpi: Review['kpis'][number]; editable: boolean; supervisorEditable: boolean; saving: boolean; onSave: (id: string, score: string, comment: string, actor: 'employee' | 'supervisor') => void }) { const [employeeScore, setEmployeeScore] = useState(kpi.employeeScore?.toString() ?? ''); const [employeeComment, setEmployeeComment] = useState(kpi.employeeComment ?? ''); const [supervisorScore, setSupervisorScore] = useState(kpi.supervisorScore?.toString() ?? ''); const [supervisorComment, setSupervisorComment] = useState(kpi.supervisorComment ?? ''); return <article className="review-item"><div className="item-title"><div><strong>{kpi.title}</strong><span>{kpi.target ? `Target: ${kpi.target}${kpi.measurementUnit ? ` ${kpi.measurementUnit}` : ''}` : 'No target specified'}</span></div><b>{kpi.weight}%</b></div>{editable && <><label>Employee score (0–100)<input type="number" min="0" max="100" value={employeeScore} disabled={saving} onChange={e => setEmployeeScore(e.target.value)} /></label><label>Employee comment<textarea value={employeeComment} disabled={saving} onChange={e => setEmployeeComment(e.target.value)} /></label><button disabled={saving || employeeScore === ''} onClick={() => onSave(kpi.id, employeeScore, employeeComment, 'employee')}>{saving ? 'Saving…' : 'Save employee score'}</button></>}{!editable && <div className="read-only-score"><strong>Employee score:</strong> {kpi.employeeScore != null ? `${Number(kpi.employeeScore).toFixed(1)}%` : 'Not scored'}{kpi.employeeComment && <p>{kpi.employeeComment}</p>}</div>}{kpi.supervisorScore != null && <div className="read-only-score"><strong>Supervisor score:</strong> {Number(kpi.supervisorScore).toFixed(1)}%{kpi.supervisorComment && <p>{kpi.supervisorComment}</p>}</div>}{supervisorEditable && <><label>Supervisor score (0–100)<input type="number" min="0" max="100" value={supervisorScore} disabled={saving} onChange={e => setSupervisorScore(e.target.value)} /></label><label>Supervisor comment<textarea value={supervisorComment} disabled={saving} onChange={e => setSupervisorComment(e.target.value)} /></label><button disabled={saving || supervisorScore === ''} onClick={() => onSave(kpi.id, supervisorScore, supervisorComment, 'supervisor')}>{saving ? 'Saving…' : 'Save supervisor score'}</button></>}</article> }
function CompetencyEditor({ competency, editable, supervisorEditable, saving, onSave }: { competency: Review['competencies'][number]; editable: boolean; supervisorEditable: boolean; saving: boolean; onSave: (id: string, rating: string, comment: string, actor: 'employee' | 'supervisor') => void }) { const [employeeRating, setEmployeeRating] = useState(competency.employeeRating?.toString() ?? ''); const [employeeComment, setEmployeeComment] = useState(competency.employeeComment ?? ''); const [supervisorRating, setSupervisorRating] = useState(competency.supervisorRating?.toString() ?? ''); const [supervisorComment, setSupervisorComment] = useState(competency.supervisorComment ?? ''); return <article className="review-item"><div className="item-title"><div><strong>{competency.competency.name}</strong><span>Weighted competency</span></div><b>{competency.weight}%</b></div>{editable && <><label>Employee rating (0–100)<input type="number" min="0" max="100" value={employeeRating} disabled={saving} onChange={e => setEmployeeRating(e.target.value)} /></label><label>Employee comment<textarea value={employeeComment} disabled={saving} onChange={e => setEmployeeComment(e.target.value)} /></label><button disabled={saving || employeeRating === ''} onClick={() => onSave(competency.id, employeeRating, employeeComment, 'employee')}>{saving ? 'Saving…' : 'Save employee rating'}</button></>}{!editable && <div className="read-only-score"><strong>Employee rating:</strong> {competency.employeeRating != null ? `${Number(competency.employeeRating).toFixed(1)}%` : 'Not rated'}{competency.employeeComment && <p>{competency.employeeComment}</p>}</div>}{competency.supervisorRating != null && <div className="read-only-score"><strong>Supervisor rating:</strong> {Number(competency.supervisorRating).toFixed(1)}%{competency.supervisorComment && <p>{competency.supervisorComment}</p>}</div>}{supervisorEditable && <><label>Supervisor rating (0–100)<input type="number" min="0" max="100" value={supervisorRating} disabled={saving} onChange={e => setSupervisorRating(e.target.value)} /></label><label>Supervisor comment<textarea value={supervisorComment} disabled={saving} onChange={e => setSupervisorComment(e.target.value)} /></label><button disabled={saving || supervisorRating === ''} onClick={() => onSave(competency.id, supervisorRating, supervisorComment, 'supervisor')}>{saving ? 'Saving…' : 'Save supervisor rating'}</button></>}</article> }
