'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api';
type Tab='units'|'unit-types'|'designations'|'assignments'|'reporting';
type Employee={id:string;employeeNumber:string;firstName:string;lastName:string};
type Unit={id:string;name:string;code:string;level?:number|null;parent?:{name:string}|null;unitType?:{name:string}|null;headEmployee?:Employee|null};
type UnitType={id:string;name:string;code:string;level?:number|null};
type Designation={id:string;name:string;code:string;gradeLevel?:string|null};
type Assignment={id:string;employee:Employee;organizationalUnit:Unit;designation?:Designation|null;supervisor?:Employee|null;isPrimary:boolean};
type Reporting={id:string;employee:Employee;reportsToEmployee:Employee;relationshipType:string};
export default function OrganizationSetupPage(){
 const router=useRouter(); const [tab,setTab]=useState<Tab>('units'); const [orgId,setOrgId]=useState(''); const [employees,setEmployees]=useState<Employee[]>([]); const [units,setUnits]=useState<Unit[]>([]); const [unitTypes,setUnitTypes]=useState<UnitType[]>([]); const [designations,setDesignations]=useState<Designation[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]); const [reporting,setReporting]=useState<Reporting[]>([]); const [error,setError]=useState('');
 async function load(path:string){const r=await fetch(`${API}${path}`,{credentials:'include'});if(r.status===401){router.replace('/login');return []}if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message??'Unable to load organization data')}return r.json()}
 async function refresh(){try{setError('');const me=await load('/auth/me');const id=me?.employee?.organizationId||'';if(!id)throw new Error('No organization is associated with this account');setOrgId(id);const [u,t,d,e,a,rr]=await Promise.all([load(`/organizations/${id}/units`),load(`/organizations/${id}/unit-types`),load(`/organizations/${id}/designations`),load('/employees'),load(`/organizations/${id}/assignments`),load(`/organizations/${id}/reporting-relationships`)]);setUnits(u);setUnitTypes(t);setDesignations(d);setEmployees(e);setAssignments(a);setReporting(rr)}catch(e){setError(e instanceof Error?e.message:'Unable to load organization data')}}
 useEffect(()=>{refresh()},[]);
 async function create(path:string,body:unknown){try{setError('');const r=await fetch(`${API}${path}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message??'Unable to save')}await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}}
 const tabs:[Tab,string][]=[['units','Hierarchy'],['unit-types','Unit types'],['designations','Designations'],['assignments','Assignments'],['reporting','Reporting']];
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>PMS</span><small>Performance Management</small></div><nav><a onClick={()=>router.push('/')}>Overview</a><a className="active">Organization Setup</a><a onClick={()=>router.push('/performance-setup')}>Performance Setup</a><a onClick={()=>router.push('/reviews')}>My Reviews</a></nav></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">PMS administration</p><h1>Organization setup</h1></div><button className="back-button" onClick={()=>router.push('/')}>Dashboard</button></header><div className="content">{error&&<p className="error">{error}</p>}<section className="panel setup-hero"><div><p className="eyebrow">Organization structure</p><h2>Define who belongs where.</h2><p className="muted">Maintain organizational units, unit types, designations, employee assignments and reporting relationships without hard-coding the organization.</p></div></section><div className="setup-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>{tab==='units'&&<Units units={units} types={unitTypes} employees={employees} create={b=>create(`/organizations/${orgId}/units`,b)}/>} {tab==='unit-types'&&<UnitTypes items={unitTypes} create={b=>create(`/organizations/${orgId}/unit-types`,b)}/>} {tab==='designations'&&<Designations items={designations} create={b=>create(`/organizations/${orgId}/designations`,b)}/>} {tab==='assignments'&&<Assignments employees={employees} units={units} designations={designations} items={assignments} create={b=>create(`/organizations/${orgId}/assignments`,b)}/>} {tab==='reporting'&&<Reporting employees={employees} items={reporting} create={b=>create(`/organizations/${orgId}/reporting-relationships`,b)}/>}</div></section></main>}
function Panel({title,description,onSubmit,children}:{title:string;description:string;onSubmit:(e:FormEvent)=>void;children:React.ReactNode}){return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Configuration</p><h3>{title}</h3><p className="muted">{description}</p></div></div><form className="setup-form" onSubmit={onSubmit}>{children}<button className="primary-action">Create</button></form></section>}
function Units({units,types,employees,create}:{units:Unit[];types:UnitType[];employees:Employee[];create:(b:unknown)=>void}){const[v,setV]=useState({name:'',code:'',description:'',parentId:'',unitTypeId:'',headEmployeeId:'',level:''});return <Panel title="Organizational units" description="Build a configurable hierarchy such as Directorate → Department → Division → Unit." onSubmit={e=>{e.preventDefault();create({...v,level:v.level?Number(v.level):undefined});setV({name:'',code:'',description:'',parentId:'',unitTypeId:'',headEmployeeId:'',level:''})}}><input placeholder="Unit name" required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/><input placeholder="Code" required value={v.code} onChange={e=>setV({...v,code:e.target.value})}/><select value={v.parentId} onChange={e=>setV({...v,parentId:e.target.value})}><option value="">No parent — top level</option>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={v.unitTypeId} onChange={e=>setV({...v,unitTypeId:e.target.value})}><option value="">No unit type</option>{types.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={v.headEmployeeId} onChange={e=>setV({...v,headEmployeeId:e.target.value})}><option value="">No head assigned</option>{employees.map(x=><option key={x.id} value={x.id}>{x.lastName}, {x.firstName}</option>)}</select><input type="number" min="0" placeholder="Hierarchy level" value={v.level} onChange={e=>setV({...v,level:e.target.value})}/><textarea placeholder="Description" value={v.description} onChange={e=>setV({...v,description:e.target.value})}/><ItemList items={units.map(x=>({id:x.id,displayName:x.name,meta:[x.code,x.unitType?.name,x.parent?.name].filter(Boolean).join(' · ')}))}/></Panel>}
function UnitTypes({items,create}:{items:UnitType[];create:(b:unknown)=>void}){const[v,setV]=useState({name:'',code:'',description:'',level:''});return <Panel title="Organizational unit types" description="Define hierarchy labels without hard-coding government-specific structures." onSubmit={e=>{e.preventDefault();create({...v,level:v.level?Number(v.level):undefined});setV({name:'',code:'',description:'',level:''})}}><input placeholder="Type name e.g. Directorate" required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/><input placeholder="Code" required value={v.code} onChange={e=>setV({...v,code:e.target.value})}/><input type="number" min="0" placeholder="Default hierarchy level" value={v.level} onChange={e=>setV({...v,level:e.target.value})}/><textarea placeholder="Description" value={v.description} onChange={e=>setV({...v,description:e.target.value})}/><ItemList items={items.map(x=>({id:x.id,displayName:x.name,meta:[x.code,x.level!=null?`Level ${x.level}`:''].filter(Boolean).join(' · ')}))}/></Panel>}
function Designations({items,create}:{items:Designation[];create:(b:unknown)=>void}){const[v,setV]=useState({name:'',code:'',description:'',gradeLevel:''});return <Panel title="Designations" description="Maintain job titles independently from security roles and organizational placement." onSubmit={e=>{e.preventDefault();create(v);setV({name:'',code:'',description:'',gradeLevel:''})}}><input placeholder="Designation" required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/><input placeholder="Code" required value={v.code} onChange={e=>setV({...v,code:e.target.value})}/><input placeholder="Grade level" value={v.gradeLevel} onChange={e=>setV({...v,gradeLevel:e.target.value})}/><textarea placeholder="Description" value={v.description} onChange={e=>setV({...v,description:e.target.value})}/><ItemList items={items.map(x=>({id:x.id,displayName:x.name,meta:[x.code,x.gradeLevel].filter(Boolean).join(' · ')}))}/></Panel>}
function Assignments({employees,units,designations,items,create}:{employees:Employee[];units:Unit[];designations:Designation[];items:Assignment[];create:(b:unknown)=>void}){const[v,setV]=useState({employeeId:'',organizationalUnitId:'',designationId:'',supervisorEmployeeId:'',isPrimary:true,startDate:'',endDate:''});return <Panel title="Employee assignments" description="Place employees in units with a primary assignment, designation and supervisor." onSubmit={e=>{e.preventDefault();create({...v,endDate:v.endDate||undefined});setV({...v,employeeId:'',organizationalUnitId:'',designationId:'',supervisorEmployeeId:'',startDate:'',endDate:''})}}><select required value={v.employeeId} onChange={e=>setV({...v,employeeId:e.target.value})}><option value="">Employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.lastName}, {x.firstName}</option>)}</select><select required value={v.organizationalUnitId} onChange={e=>setV({...v,organizationalUnitId:e.target.value})}><option value="">Organizational unit</option>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={v.designationId} onChange={e=>setV({...v,designationId:e.target.value})}><option value="">Use employee designation</option>{designations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={v.supervisorEmployeeId} onChange={e=>setV({...v,supervisorEmployeeId:e.target.value})}><option value="">No assignment supervisor</option>{employees.map(x=><option key={x.id} value={x.id}>{x.lastName}, {x.firstName}</option>)}</select><label>Start date<input type="date" required value={v.startDate} onChange={e=>setV({...v,startDate:e.target.value})}/></label><label>End date<input type="date" value={v.endDate} onChange={e=>setV({...v,endDate:e.target.value})}/></label><label className="setup-check"><input type="checkbox" checked={v.isPrimary} onChange={e=>setV({...v,isPrimary:e.target.checked})}/> Primary assignment</label><ItemList items={items.map(x=>({id:x.id,displayName:`${x.employee.firstName} ${x.employee.lastName} · ${x.organizationalUnit.name}`,meta:[x.designation?.name,x.supervisor?`Supervisor: ${x.supervisor.firstName} ${x.supervisor.lastName}`:''].filter(Boolean).join(' · ')}))}/></Panel>}
function Reporting({employees,items,create}:{employees:Employee[];items:Reporting[];create:(b:unknown)=>void}){const[v,setV]=useState({employeeId:'',reportsToEmployeeId:'',relationshipType:'DIRECT',startDate:'',endDate:''});return <Panel title="Reporting relationships" description="Maintain reporting separately from placement to support direct, acting, matrix and secondary relationships." onSubmit={e=>{e.preventDefault();create({...v,endDate:v.endDate||undefined});setV({...v,employeeId:'',reportsToEmployeeId:'',startDate:'',endDate:''})}}><select required value={v.employeeId} onChange={e=>setV({...v,employeeId:e.target.value})}><option value="">Employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.lastName}, {x.firstName}</option>)}</select><select required value={v.reportsToEmployeeId} onChange={e=>setV({...v,reportsToEmployeeId:e.target.value})}><option value="">Reports to</option>{employees.map(x=><option key={x.id} value={x.id}>{x.lastName}, {x.firstName}</option>)}</select><select value={v.relationshipType} onChange={e=>setV({...v,relationshipType:e.target.value})}><option value="DIRECT">Direct</option><option value="ACTING">Acting</option><option value="MATRIX">Matrix</option><option value="SECONDARY">Secondary</option></select><label>Start date<input type="date" required value={v.startDate} onChange={e=>setV({...v,startDate:e.target.value})}/></label><label>End date<input type="date" value={v.endDate} onChange={e=>setV({...v,endDate:e.target.value})}/></label><ItemList items={items.map(x=>({id:x.id,displayName:`${x.employee.firstName} ${x.employee.lastName} → ${x.reportsToEmployee.firstName} ${x.reportsToEmployee.lastName}`,meta:x.relationshipType}))}/></Panel>}
function ItemList({items}:{items:{id:string;displayName:string;meta?:string}[]}){return <div className="setup-list">{items.length===0?<p className="muted">Nothing configured yet.</p>:items.map(x=><div className="setup-row" key={x.id}><div><strong>{x.displayName}</strong><span>{x.meta}</span></div></div>)}</div>}
